on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: Setup Dependencies
        run: bun install
      - name: Build Repo
        run: bun run build
      - name: Commit Build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist -f
          git commit -m ""
          git push
